language: go
go_import_path: github.com/goeuro/ingress-generator-kit
go:
- 1.9
install:
- bin/init.sh
script:
- bin/test.sh
- VERSION="$TRAVIS_TAG-$TRAVIS_COMMIT" bin/cross-compile.sh
after_success:
- mv overalls.coverprofile coverage.txt
- bash <(curl -s https://codecov.io/bash) -t 1e11888e-6fb8-458d-b0d9-515b49b74529
deploy:
  provider: releases
  api_key:
    secure: jmHHafXk5voPSeNJZauF+cc08X4bqVZAvNJP1nEn6GcnMZOicjNRR0OYswvcgfRyrOUVVsrg8DjOxux8xpwIQmCGWdRZga/eRp4dm25eFD4qjF9Oe81k/3QfWB9LtJWp7mwk5IfjooxMQT2mivJiBFGBEd+a9Q3Nortg3PDBMptViALKUb5xMvBkjn0uq0yV8+1GMe5bdJ+Vz4fB4Q2DFwdIfh65V1Ke4P4fsXqjUyLKV4O/baMzn0TREM8FeAwA6k4Fzk8vliI4Q1DUoZ2hkpSaVx/63oArJ5Wh8at3+09jI10LxglG4x0y19yXaHHW+KIFWTlo/RVlSxHWMh+PyrUKP5N0GU+N5/GUwHWFLJzT5F88TtWJ3MXH51kkNipLmHezS3JB6GtxZE1tPrdNjNpXZTG0u9Q+SrKjxQS3O6pA7y68OAoLdYi223d3ogoGckpIgCl4woApJIusGSOfbU6Z7YrZH4UBjRas3zP2cdzOICSsm07Ncw4Zi+omYaGAyHEow7AzNGaH5YpxdjAqYrk06qL92Zurq8ZbDXPtM/W19rtGXQrD3TOEX8Eo1xH53eTe3D0EjxZRTAvfQyLFd9G9uMcPYwqy9r1oGzqVh/OAoOxaepDg0q0T1HOvWOUiX5k00u1PRTiobhKjivxo/ZcClsUFop0khAziyGCM2Ac=
  file: gen/ingress-generator-*
  on:
    repo: goeuro/ingress-generator-kit
    branch: none
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].+$"
notifications:
  email: false
